name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./twitter-extension

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Use Node.js v18.16.0
      uses: actions/setup-node@v3
      with:
        node-version: v18.16.0
        cache: 'npm'
        cache-dependency-path: ./twitter-extension/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Get package version
      id: version
      run: echo "::set-output name=version::$(node -p "require('./package-lock.json').packages[''].version")"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: heitan-v${{ steps.version.outputs.version }}
        path: ./twitter-extension/build/chrome-mv3-prod/*
