name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./twitter-extension

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js v18.16.0
      uses: actions/setup-node@v3
      with:
        node-version: v18.16.0
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Zip Build Artifacts
      run: zip -r build/chrome-mv3-prod.zip build/chrome-mv3-prod/*

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/chrome-mv3-prod.zip
