name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./twitter-extension

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Use Node.js v18.16.0
      uses: actions/setup-node@v3
      with:
        node-version: v18.16.0
        cache: 'npm'
        cache-dependency-path: ./twitter-extension/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Get package version
      id: version
      run: |
        VERSION=$(node -p "require('./package-lock.json').packages[''].version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: heitan-v${{ env.VERSION }}
        path: ./twitter-extension/build/chrome-mv3-prod/*
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release Notes for version ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Check
        run: ls

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./twitter-extension/build/chrome-mv3-prod/
          asset_name: heitan-v${{ env.VERSION }}.zip
          asset_content_type: application/zip
